"""Per-session WireGuard identity.

Each session gets a fresh key pair on both ends.  mitmproxy's WireGuard mode
accepts exactly one peer, so a session's tunnel is usable by exactly one guest:
a leaked config from an old session authenticates to nothing.

The guest receives only its own private key and the server's *public* key. The
server private key never leaves the host.
"""

from __future__ import annotations

import json
import textwrap
from dataclasses import dataclass
from pathlib import Path

from .config import GUEST_TUNNEL_ADDR, TUNNEL_DNS_ADDR, write_private_file

#: 1420 = 1500 - 60 (IPv6 header) - 20 (WireGuard overhead), the usual safe
#: value; too high and TLS handshakes stall in ways that look like policy bugs.
DEFAULT_MTU = 1420


def _wg():
    import mitmproxy_rs.wireguard as wg  # imported lazily: needs the native ext

    return wg


def generate_key() -> str:
    return _wg().genkey()


def public_key(private_key: str) -> str:
    return _wg().pubkey(private_key)


@dataclass
class WireGuardIdentity:
    """The key material for one session's tunnel."""

    server_key: str  # mitmproxy side, private
    client_key: str  # guest side, private
    listen_host: str = "127.0.0.1"
    listen_port: int = 51820

    @classmethod
    def generate(cls, listen_host: str = "127.0.0.1", listen_port: int = 51820) -> WireGuardIdentity:
        return cls(
            server_key=generate_key(),
            client_key=generate_key(),
            listen_host=listen_host,
            listen_port=listen_port,
        )

    @property
    def server_public(self) -> str:
        return public_key(self.server_key)

    @property
    def client_public(self) -> str:
        return public_key(self.client_key)

    # -- host side ----------------------------------------------------------

    def write_mitm_conf(self, path: Path) -> Path:
        """mitmproxy's wireguard-mode config. Contains both private keys."""
        return write_private_file(
            path,
            json.dumps({"server_key": self.server_key, "client_key": self.client_key}, indent=4),
        )

    @classmethod
    def load_mitm_conf(cls, path: Path, listen_host: str, listen_port: int) -> WireGuardIdentity:
        data = json.loads(path.read_text())
        return cls(
            server_key=data["server_key"],
            client_key=data["client_key"],
            listen_host=listen_host,
            listen_port=listen_port,
        )

    # -- guest side ---------------------------------------------------------

    def guest_config(
        self,
        endpoint_host: str | None = None,
        endpoint_port: int | None = None,
        mtu: int = DEFAULT_MTU,
    ) -> str:
        """wg-quick config for the guest.

        ``AllowedIPs = 0.0.0.0/0`` is what makes the tunnel the guest's default
        route.  IPv6 is deliberately absent: mitmproxy's WireGuard mode hands
        out an IPv4 address only, and an IPv6 route that is not tunnelled would
        be exactly the bypass the spec forbids - the guest bootstrap disables
        IPv6 outright.

        ``endpoint_host``/``endpoint_port`` are the address *the guest sees* -
        the L2 gateway's virtual endpoint - which is not where mitmproxy is
        actually listening. The gateway does that translation, and the guest
        never learns the host-side port. Defaulting them to the real listener
        is only for host-only setups with no gateway in between.
        """
        endpoint = endpoint_host or self.listen_host
        port = endpoint_port or self.listen_port
        return (
            textwrap.dedent(
                f"""
                # Generated by agentsandbox. One peer, one session.
                [Interface]
                PrivateKey = {self.client_key}
                Address = {GUEST_TUNNEL_ADDR}/32
                DNS = {TUNNEL_DNS_ADDR}
                MTU = {mtu}

                [Peer]
                PublicKey = {self.server_public}
                AllowedIPs = 0.0.0.0/0
                Endpoint = {endpoint}:{port}
                PersistentKeepalive = 25
                """
            ).strip()
            + "\n"
        )

    def write_guest_config(
        self,
        path: Path,
        endpoint_host: str | None = None,
        endpoint_port: int | None = None,
    ) -> Path:
        return write_private_file(path, self.guest_config(endpoint_host, endpoint_port))
